//
// Created by 盧威任 on 5/6/24.
//

#ifndef PRACTICALTOOLSFORSIMPLEDESIGN_IORDERABLE_HPP
#define PRACTICALTOOLSFORSIMPLEDESIGN_IORDERABLE_HPP
class IOrderable {};
#endif // PRACTICALTOOLSFORSIMPLEDESIGN_IORDERABLE_HPP
