//
// Created by 盧威任 on 4/1/24.
//

#ifndef PRACTICALTOOLSFORSIMPLEDESIGN_MOVEDIRECTION_HPP
#define PRACTICALTOOLSFORSIMPLEDESIGN_MOVEDIRECTION_HPP
enum class MoveDirection {
    UP,
    UP_RIGHT,
    UP_LEFT,
    RIGHT,
    LEFT,
    DOWN_RIGHT,
    DOWN_LEFT,
    DOWN,
    IDLE
};
#endif // PRACTICALTOOLSFORSIMPLEDESIGN_MOVEDIRECTION_HPP
