//
// Created by 盧威任 on 2/11/24.
//

#ifndef PRACTICALTOOLSFORSIMPLEDESIGN_CAMERA_HPP
#define PRACTICALTOOLSFORSIMPLEDESIGN_CAMERA_HPP

class CameraClass{


};

#endif // PRACTICALTOOLSFORSIMPLEDESIGN_CAMERA_HPP
