//
// Created by 盧威任 on 2/14/24.
//

#ifndef PRACTICALTOOLSFORSIMPLEDESIGN_SETTINGS_HPP
#define PRACTICALTOOLSFORSIMPLEDESIGN_SETTINGS_HPP

extern int WINDOWHEIGHT=1080;
extern int WINDOWWIDTH=1920;


#endif // PRACTICALTOOLSFORSIMPLEDESIGN_SETTINGS_HPP
